#!/Users/fde-fede/goinfre/miniconda3/envs/42AI-fde-fede/bin/python3
from PIL import Image
from PIL.ExifTags import TAGS
import sys
import os.path
import time

def get_exif_data(filename):
    with Image.open(filename) as img:
        exifdata = img.getexif()
        if exifdata:
            exif = {}
            for tag_id, value in exifdata.items():
                tag = TAGS.get(tag_id, tag_id)
                exif[tag] = value
            return exif
        else:
            return None
        
if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: scorpion.py FILE1 [FILE2 ...]")
        sys.exit(1)

    for filename in sys.argv[1:]:
        if not os.path.exists(filename):
            print("File not found:", filename)
        else:
            print("File: %s" % filename)
            exif = get_exif_data(filename)
            print("Creation date:", time.ctime(os.path.getctime(filename)))
            print("Modification date:", time.ctime(os.path.getmtime(filename)))
            print("Size:", os.path.getsize(filename), "bytes")
            if exif:
                print("EXIF data:")
                for tag, value in exif.items():
                    print("%s = %s" % (tag, value))
            else:
                print("No EXIF data found.")
        